import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { validatePaymentRequest } from "../src/lib/storefront/payment-contract.ts";
import { assertFlowPaymentUrl, createFlowGateway, FlowRequestError, normalizeFlowProviderError } from "../src/lib/payments/flow.ts";

const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
const migration="../supabase/migrations/20260831225257_web_flow_payments.sql";
const functionBlock=(sql,name)=>sql.match(new RegExp(`create or replace function public\\.${name}\\([\\s\\S]*?\\n\\$\\$;`,"i"))?.[0]??"";
process.env.FLOW_API_KEY="TEST_FLOW_API_KEY_NOT_REAL";process.env.FLOW_SECRET_KEY="TEST_FLOW_SECRET_NOT_REAL";process.env.FLOW_API_BASE_URL="https://sandbox.flow.cl/api";process.env.FLOW_ENVIRONMENT="sandbox";process.env.APP_BASE_URL="https://badge-outpost-chaplain.ngrok-free.dev";

test("errores Flow normalizan codigo numerico o string y campos allowlisted",()=>{assert.deepEqual(normalizeFlowProviderError({code:123,message:"Dato invalido"},400),{code:"123",message:"Dato invalido"});assert.deepEqual(normalizeFlowProviderError({code:"123",message:"Dato invalido"},400),{code:"123",message:"Dato invalido"});assert.deepEqual(normalizeFlowProviderError({error:"Solicitud rechazada"},400),{code:"http_400",message:"Solicitud rechazada"});assert.deepEqual(normalizeFlowProviderError({unexpected:{apiKey:"SECRET"},token:"SECRET"},400,["SECRET"]),{code:"http_400",message:null});assert.deepEqual(normalizeFlowProviderError(null,400),{code:"http_400",message:null});});
test("mensaje Flow elimina HTML, controles, secretos y limita longitud",()=>{const secret="TEST_FLOW_SECRET_NOT_REAL";const normalized=normalizeFlowProviderError({code:400,message:`<script>alert(1)</script> Error\u0000 cliente@example.com token=ABC apiKey=${secret} ${"x".repeat(500)}`},400,[secret]);assert.equal(normalized.code,"400");assert.ok(normalized.message);assert.ok(normalized.message.length<=240);assert.doesNotMatch(normalized.message,/<|>|ABC|TEST_FLOW_SECRET_NOT_REAL|cliente@example.com|\u0000/);assert.match(normalized.message,/token=\[redacted\]/);assert.match(normalized.message,/\[redacted-email\]/);});
test("gateway conserva error sanitizado sin exponer body completo",async()=>{const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({code:1702,message:"Campo invalido <b>paymentMethod</b>",token:"NO_PERSISTIR",extra:{apiKey:"NO_PERSISTIR"}}),{status:400,headers:{"content-type":"application/json"}});try{const gateway=createFlowGateway();await assert.rejects(gateway.createPayment({commerceOrder:"COL-TEST",subject:"Pedido COL-TEST",currency:"CLP",amount:54990,email:"test@example.com",paymentMethod:9,urlConfirmation:"https://example.com/c",urlReturn:"https://example.com/r",optional:"{}"}),(error)=>{assert.ok(error instanceof FlowRequestError);assert.equal(error.code,"1702");assert.equal(error.httpStatus,400);assert.equal(error.uncertain,false);assert.match(error.message,/^Flow rechaz/);assert.equal(error.providerMessage,"Campo invalido paymentMethod");assert.doesNotMatch(JSON.stringify(error),/NO_PERSISTIR/);return true;});}finally{globalThis.fetch=originalFetch;}});
test("body no JSON conserva fallback y rechazos inciertos no cambian",async()=>{const originalFetch=globalThis.fetch;try{globalThis.fetch=async()=>new Response("not-json",{status:400});await assert.rejects(createFlowGateway().createPayment({commerceOrder:"COL-TEST-400",subject:"Pedido",currency:"CLP",amount:1,email:"test@example.com",paymentMethod:9,urlConfirmation:"https://example.com/c",urlReturn:"https://example.com/r",optional:"{}"}),(error)=>error instanceof FlowRequestError&&error.code==="http_400"&&error.providerMessage===null&&!error.uncertain);globalThis.fetch=async()=>new Response(JSON.stringify({code:503,message:"Temporal"}),{status:503});await assert.rejects(createFlowGateway().createPayment({commerceOrder:"COL-TEST-503",subject:"Pedido",currency:"CLP",amount:1,email:"test@example.com",paymentMethod:9,urlConfirmation:"https://example.com/c",urlReturn:"https://example.com/r",optional:"{}"}),(error)=>error instanceof FlowRequestError&&error.code==="503"&&error.providerMessage==="Temporal"&&error.uncertain);}finally{globalThis.fetch=originalFetch;}});
test("attempt persiste detalle provider sanitizado y mantiene mensaje publico generico",async()=>{const source=await read("../src/lib/storefront/payment-server.ts"),adapter=await read("../src/lib/payments/flow.ts");assert.match(source,/p_error_message:failure\.providerMessage\?\?failure\.message/);assert.match(adapter,/new FlowRequestError\("Flow rechazó la solicitud\.", provider\.code/);assert.doesNotMatch(source,/request body|headers sensibles/i);});

test("4E es transaccional, aditiva y separada de commerce legacy",async()=>{const sql=await read(migration);assert.match(sql,/^begin;/i);assert.match(sql,/commit;\s*$/i);assert.doesNotMatch(sql,/drop\s+(table|column)|alter table public\.commerce_|update public\.commerce_/i);});
test("modelo web persiste pagos, intentos y eventos idempotentes",async()=>{const sql=await read(migration);for(const table of["web_payments","web_payment_attempts","web_payment_events"])assert.match(sql,new RegExp(`create table public\\.${table}`));for(const state of["pending","paid","failed","cancelled","expired","uncertain","refund_pending","refunded","creating","ready"])assert.match(sql,new RegExp(`'${state}'`));assert.match(sql,/unique \(payment_id, idempotency_key\)/);assert.match(sql,/unique \(provider, payload_hash\)/);assert.match(sql,/flow_token text unique/);assert.match(sql,/commerce_order text not null unique/);});
test("RLS bloquea clientes y RPC de pago son solo service_role",async()=>{const sql=await read(migration);for(const table of["web_payments","web_payment_attempts","web_payment_events"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));for(const fn of["claim_web_flow_payment","complete_web_flow_payment_attempt","fail_web_flow_payment_attempt","get_web_flow_callback_context","process_web_flow_event","expire_web_pending_payments","get_web_payment_result"]){assert.match(sql,new RegExp(`revoke all on function public\\.${fn}[\\s\\S]*?from public,anon,authenticated`));assert.match(sql,new RegExp(`grant execute on function public\\.${fn}[\\s\\S]*?to service_role`));}});
test("claim valida propiedad guest, pedido, reserva y monto persistido",async()=>{const sql=await read(migration);assert.match(sql,/where token_hash=p_token_hash/);assert.match(sql,/id=p_order_id and session_id=selected_session\.id/);assert.match(sql,/selected_reservation\.status <> 'active'/);assert.match(sql,/selected_reservation\.expires_at <= now\(\)/);assert.match(sql,/selected_order\.total <> selected_order\.items_subtotal-selected_order\.discount_total\+selected_order\.shipping_total/);assert.match(sql,/selected_order\.items_subtotal <> \(select coalesce\(sum\(item\.line_subtotal\),0\)/);});
test("doble click solo entrega ownership al insert que creó el attempt",async()=>{const sql=await read(migration);assert.match(sql,/claim_owned boolean := false/);assert.match(sql,/claim_owned := true/);assert.match(sql,/'claimOwned',claim_owned/);assert.match(sql,/unique \(payment_id, idempotency_key\)/);});
test("commerceOrder web es inequívoco y retries no colisionan",async()=>{const sql=await read(migration);assert.match(sql,/case when next_attempt=1 then selected_order\.order_number else selected_order\.order_number\|\|'-A'\|\|next_attempt end/);assert.doesNotMatch(sql,/instagram_conversations|external_user_id/);});
test("callback valida token, Flow order, commerceOrder, monto y moneda",async()=>{const sql=await read(migration),server=await read("../src/lib/storefront/payment-server.ts"),adapter=await read("../src/lib/payments/flow.ts");assert.match(sql,/provider_order_id<>p_provider_order_id/);assert.match(sql,/commerce_order<>p_commerce_order/);assert.match(sql,/selected_payment\.amount<>p_amount/);assert.match(sql,/selected_payment\.currency<>p_currency/);assert.match(server,/gateway\.getStatus\(token\)/);assert.match(server,/assertFlowPaymentStatusMatches/);assert.match(adapter,/Flow payment verification mismatch/);});
test("approved consume reserva y stock exactamente dentro de una función",async()=>{const sql=await read(migration);assert.match(sql,/for update/);assert.match(sql,/lock_web_stock_variants\(variant_ids\)/);assert.match(sql,/set stock=variant\.stock-item\.quantity/);assert.match(sql,/variant\.stock>=item\.quantity/);assert.match(sql,/status='consumed',consumed_at=now\(\)/);assert.match(sql,/web_payments set status='paid'/);assert.match(sql,/web_orders set status='paid'/);assert.match(sql,/web_carts set status='converted',converted_at=now\(\)/);});
test("callback duplicado no vuelve a consumir stock",async()=>{const sql=await read(migration);assert.match(sql,/on conflict\(provider,payload_hash\) do nothing/);assert.match(sql,/if not found then return jsonb_build_object\('handled',true,'duplicate',true/);assert.match(sql,/selected_payment\.status='paid'/);});
test("late payment readquiere disponibilidad o conserva pago en review",async()=>{const sql=await read(migration);assert.match(sql,/reservation_is_current/);assert.match(sql,/web_variant_available_stock\(item\.variant_id\)<item\.quantity/);assert.match(sql,/stock_exception=true/);assert.match(sql,/status='payment_review'/);assert.match(sql,/event_type='paid_stock_exception'/);assert.match(sql,/greatest|variant\.stock>=item\.quantity/);});
test("fallo libera reserva sin tocar stock y no reabre un carrito incoherente",async()=>{const sql=await read(migration),fn=functionBlock(sql,"process_web_flow_event");assert.match(fn,/release_reason=case when p_provider_status=3 then 'flow_failed' else 'flow_cancelled'/);const failureBranch=fn.split("elsif p_provider_status=1 then")[1]?.split("end if;")[0]??"";assert.doesNotMatch(failureBranch,/product_variants|set stock=/i);assert.doesNotMatch(sql,/web_carts set status='open'/);});
test("expiración sin pago no depende del cron para disponibilidad",async()=>{const sql=await read(migration),fn=functionBlock(sql,"expire_web_pending_payments");assert.match(fn,/reservation\.expires_at<=now\(\)/);assert.match(fn,/status='expired',released_at=now\(\),release_reason='payment_timeout'/);assert.doesNotMatch(fn,/product_variants|set stock=/i);});
test("el navegador solo puede enviar orderId e idempotencyKey",()=>{const valid={orderId:"11111111-1111-4111-8111-111111111111",idempotencyKey:"22222222-2222-4222-8222-222222222222"};assert.deepEqual(validatePaymentRequest(valid),valid);for(const key of["amount","currency","status","paymentUrl","commerceOrder"])assert.throws(()=>validatePaymentRequest({...valid,[key]:1}),/campos no permitidos/);});
test("URL de pago debe pertenecer a Flow",()=>{assert.equal(assertFlowPaymentUrl("https://sandbox.flow.cl/app/web/pay.php?token=ABC").hostname,"sandbox.flow.cl");for(const url of["http://sandbox.flow.cl/pay","https://flow.cl.evil.example/pay","https://user:pass@flow.cl/pay"])assert.throws(()=>assertFlowPaymentUrl(url));});
test("creación usa monto DB, callbacks oficiales y nunca registra secretos",async()=>{const source=await read("../src/lib/storefront/payment-server.ts");assert.match(source,/amount:Number\(claim\.amount\)/);assert.match(source,/flowCallbackUrls\(\)/);assert.match(source,/channel:\"web\"/);assert.doesNotMatch(source,/console\.|FLOW_SECRET_KEY|FLOW_API_KEY/);});
test("retorno no confirma pago y resultado consulta estado por cookie",async()=>{const ret=await read("../src/app/api/payments/flow/return/route.ts"),page=await read("../src/components/storefront/payment-result.tsx"),status=await read("../src/app/api/storefront/payment/status/route.ts");assert.doesNotMatch(ret,/confirmWebFlowToken|process_web_flow_event|paid/);assert.match(ret,/flowPublicUrl\("\/payment-result"\)/);assert.doesNotMatch(ret,/request\.url|headers\.get\(["'](?:host|x-forwarded)/i);assert.match(ret,/303/);assert.match(page,/Estamos confirmando tu pago/);assert.match(page,/api\/storefront\/payment\/status/);assert.match(status,/CART_COOKIE/);assert.doesNotMatch(status,/searchParams|orderId/);});
test("checkout crea pedido, reclama Flow y redirige solo a la URL backend",async()=>{const page=await read("../src/components/storefront/checkout-page.tsx");assert.match(page,/api\/storefront\/checkout/);assert.match(page,/api\/storefront\/payment\/flow/);assert.match(page,/window\.location\.assign\(payment\.paymentUrl\)/);assert.doesNotMatch(page,/amount:/);});
test("callback distingue web de legacy sin heurísticas",async()=>{const server=await read("../src/lib/storefront/payment-server.ts"),route=await read("../src/app/api/payments/flow/confirmation/route.ts");assert.match(server,/get_web_flow_callback_context/);assert.match(server,/if\(!contextResult\.data\)return\{handled:false\}/);assert.match(route,/confirmWebFlowToken/);assert.doesNotMatch(route,/commerce_|instagram/i);});

test("callback delega normalización y comparación estricta al adapter Flow",async()=>{const server=await read("../src/lib/storefront/payment-server.ts"),adapter=await read("../src/lib/payments/flow.ts");assert.match(server,/assertFlowPaymentStatusMatches\(status/);assert.doesNotMatch(server,/status\.amount\s*!==/);assert.match(adapter,/parseFlowPaymentStatus/);assert.match(adapter,/strictNonNegativeInteger/);});
test("configuración Flow rechaza callbacks locales y construye rutas con URL",async()=>{const adapter=await read("../src/lib/payments/flow.ts"),origin=await read("../src/lib/public-origin.ts");assert.match(adapter,/requirePublicAppOrigin\(\)/);assert.match(origin,/hostname === "localhost"/);assert.match(origin,/ipv4\[0\] === 127/);assert.match(origin,/parsed\.protocol !== "https:"/);assert.match(adapter,/return new URL\(pathname, appBaseUrl\)/);assert.match(adapter,/flowPublicUrl\("\/api\/payments\/flow\/confirmation"/);assert.match(adapter,/flowPublicUrl\("\/api\/payments\/flow\/return"/);});
