import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { validatePaymentRequest } from "../src/lib/storefront/payment-contract.ts";
import { assertFlowPaymentUrl } from "../src/lib/payments/flow.ts";

const read=(path)=>readFile(new URL(path,import.meta.url),"utf8");
const migration="../supabase/migrations/20260831225257_web_flow_payments.sql";
const functionBlock=(sql,name)=>sql.match(new RegExp(`create or replace function public\\.${name}\\([\\s\\S]*?\\n\\$\\$;`,"i"))?.[0]??"";

test("4E es transaccional, aditiva y separada de commerce legacy",async()=>{const sql=await read(migration);assert.match(sql,/^begin;/i);assert.match(sql,/commit;\s*$/i);assert.doesNotMatch(sql,/drop\s+(table|column)|alter table public\.commerce_|update public\.commerce_/i);});
test("modelo web persiste pagos, intentos y eventos idempotentes",async()=>{const sql=await read(migration);for(const table of["web_payments","web_payment_attempts","web_payment_events"])assert.match(sql,new RegExp(`create table public\\.${table}`));for(const state of["pending","paid","failed","cancelled","expired","uncertain","refund_pending","refunded","creating","ready"])assert.match(sql,new RegExp(`'${state}'`));assert.match(sql,/unique \(payment_id, idempotency_key\)/);assert.match(sql,/unique \(provider, payload_hash\)/);assert.match(sql,/flow_token text unique/);assert.match(sql,/commerce_order text not null unique/);});
test("RLS bloquea clientes y RPC de pago son solo service_role",async()=>{const sql=await read(migration);for(const table of["web_payments","web_payment_attempts","web_payment_events"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));for(const fn of["claim_web_flow_payment","complete_web_flow_payment_attempt","fail_web_flow_payment_attempt","get_web_flow_callback_context","process_web_flow_event","expire_web_pending_payments","get_web_payment_result"]){assert.match(sql,new RegExp(`revoke all on function public\\.${fn}[\\s\\S]*?from public,anon,authenticated`));assert.match(sql,new RegExp(`grant execute on function public\\.${fn}[\\s\\S]*?to service_role`));}});
test("claim valida propiedad guest, pedido, reserva y monto persistido",async()=>{const sql=await read(migration);assert.match(sql,/where token_hash=p_token_hash/);assert.match(sql,/id=p_order_id and session_id=selected_session\.id/);assert.match(sql,/selected_reservation\.status <> 'active'/);assert.match(sql,/selected_reservation\.expires_at <= now\(\)/);assert.match(sql,/selected_order\.total <> selected_order\.items_subtotal-selected_order\.discount_total\+selected_order\.shipping_total/);assert.match(sql,/selected_order\.items_subtotal <> \(select coalesce\(sum\(item\.line_subtotal\),0\)/);});
test("doble click solo entrega ownership al insert que creó el attempt",async()=>{const sql=await read(migration);assert.match(sql,/claim_owned boolean := false/);assert.match(sql,/claim_owned := true/);assert.match(sql,/'claimOwned',claim_owned/);assert.match(sql,/unique \(payment_id, idempotency_key\)/);});
test("commerceOrder web es inequívoco y retries no colisionan",async()=>{const sql=await read(migration);assert.match(sql,/case when next_attempt=1 then selected_order\.order_number else selected_order\.order_number\|\|'-A'\|\|next_attempt end/);assert.doesNotMatch(sql,/instagram_conversations|external_user_id/);});
test("callback valida token, Flow order, commerceOrder, monto y moneda",async()=>{const sql=await read(migration),server=await read("../src/lib/storefront/payment-server.ts");assert.match(sql,/provider_order_id<>p_provider_order_id/);assert.match(sql,/commerce_order<>p_commerce_order/);assert.match(sql,/selected_payment\.amount<>p_amount/);assert.match(sql,/selected_payment\.currency<>p_currency/);assert.match(server,/gateway\.getStatus\(token\)/);assert.match(server,/Flow payment verification mismatch/);});
test("approved consume reserva y stock exactamente dentro de una función",async()=>{const sql=await read(migration);assert.match(sql,/for update/);assert.match(sql,/lock_web_stock_variants\(variant_ids\)/);assert.match(sql,/set stock=variant\.stock-item\.quantity/);assert.match(sql,/variant\.stock>=item\.quantity/);assert.match(sql,/status='consumed',consumed_at=now\(\)/);assert.match(sql,/web_payments set status='paid'/);assert.match(sql,/web_orders set status='paid'/);assert.match(sql,/web_carts set status='converted',converted_at=now\(\)/);});
test("callback duplicado no vuelve a consumir stock",async()=>{const sql=await read(migration);assert.match(sql,/on conflict\(provider,payload_hash\) do nothing/);assert.match(sql,/if not found then return jsonb_build_object\('handled',true,'duplicate',true/);assert.match(sql,/selected_payment\.status='paid'/);});
test("late payment readquiere disponibilidad o conserva pago en review",async()=>{const sql=await read(migration);assert.match(sql,/reservation_is_current/);assert.match(sql,/web_variant_available_stock\(item\.variant_id\)<item\.quantity/);assert.match(sql,/stock_exception=true/);assert.match(sql,/status='payment_review'/);assert.match(sql,/event_type='paid_stock_exception'/);assert.match(sql,/greatest|variant\.stock>=item\.quantity/);});
test("fallo libera reserva sin tocar stock y no reabre un carrito incoherente",async()=>{const sql=await read(migration),fn=functionBlock(sql,"process_web_flow_event");assert.match(fn,/release_reason=case when p_provider_status=3 then 'flow_failed' else 'flow_cancelled'/);const failureBranch=fn.split("elsif p_provider_status=1 then")[1]?.split("end if;")[0]??"";assert.doesNotMatch(failureBranch,/product_variants|set stock=/i);assert.doesNotMatch(sql,/web_carts set status='open'/);});
test("expiración sin pago no depende del cron para disponibilidad",async()=>{const sql=await read(migration),fn=functionBlock(sql,"expire_web_pending_payments");assert.match(fn,/reservation\.expires_at<=now\(\)/);assert.match(fn,/status='expired',released_at=now\(\),release_reason='payment_timeout'/);assert.doesNotMatch(fn,/product_variants|set stock=/i);});
test("el navegador solo puede enviar orderId e idempotencyKey",()=>{const valid={orderId:"11111111-1111-4111-8111-111111111111",idempotencyKey:"22222222-2222-4222-8222-222222222222"};assert.deepEqual(validatePaymentRequest(valid),valid);for(const key of["amount","currency","status","paymentUrl","commerceOrder"])assert.throws(()=>validatePaymentRequest({...valid,[key]:1}),/campos no permitidos/);});
test("URL de pago debe pertenecer a Flow",()=>{assert.equal(assertFlowPaymentUrl("https://sandbox.flow.cl/app/web/pay.php?token=ABC").hostname,"sandbox.flow.cl");for(const url of["http://sandbox.flow.cl/pay","https://flow.cl.evil.example/pay","https://user:pass@flow.cl/pay"])assert.throws(()=>assertFlowPaymentUrl(url));});
test("creación usa monto DB, callbacks oficiales y nunca registra secretos",async()=>{const source=await read("../src/lib/storefront/payment-server.ts");assert.match(source,/amount:Number\(claim\.amount\)/);assert.match(source,/flowCallbackUrls\(\)/);assert.match(source,/channel:\"web\"/);assert.doesNotMatch(source,/console\.|FLOW_SECRET_KEY|FLOW_API_KEY/);});
test("retorno no confirma pago y resultado consulta estado por cookie",async()=>{const ret=await read("../src/app/api/payments/flow/return/route.ts"),page=await read("../src/components/storefront/payment-result.tsx"),status=await read("../src/app/api/storefront/payment/status/route.ts");assert.doesNotMatch(ret,/confirmWebFlowToken|process_web_flow_event|paid/);assert.match(ret,/303/);assert.match(page,/Estamos confirmando tu pago/);assert.match(page,/api\/storefront\/payment\/status/);assert.match(status,/CART_COOKIE/);assert.doesNotMatch(status,/searchParams|orderId/);});
test("checkout crea pedido, reclama Flow y redirige solo a la URL backend",async()=>{const page=await read("../src/components/storefront/checkout-page.tsx");assert.match(page,/api\/storefront\/checkout/);assert.match(page,/api\/storefront\/payment\/flow/);assert.match(page,/window\.location\.assign\(payment\.paymentUrl\)/);assert.doesNotMatch(page,/amount:/);});
test("callback distingue web de legacy sin heurísticas",async()=>{const server=await read("../src/lib/storefront/payment-server.ts"),route=await read("../src/app/api/payments/flow/confirmation/route.ts");assert.match(server,/get_web_flow_callback_context/);assert.match(server,/if\(!contextResult\.data\)return\{handled:false\}/);assert.match(route,/confirmWebFlowToken/);assert.doesNotMatch(route,/commerce_|instagram/i);});
