import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {createResendProvider,EmailProviderError} from "../src/lib/email/resend.ts";

const root=new URL("../",import.meta.url);const migration=new URL("../supabase/migrations/20260908011256_web_expiration_order_email_outbox.sql",import.meta.url);const read=(path)=>readFile(new URL(path,root),"utf8");

test("P3 crea outbox aditivo, transaccional y con RLS",async()=>{const sql=await readFile(migration,"utf8");assert.match(sql,/^begin;/);assert.match(sql,/commit;\s*$/);assert.match(sql,/create table public\.web_order_email_events/);assert.match(sql,/unique \(order_id, event_type\)/);assert.match(sql,/enable row level security/);assert.match(sql,/revoke all on table public\.web_order_email_events from public, anon, authenticated/);assert.doesNotMatch(sql,/drop\s+(table|column)|delete from/i);});

test("email nace al transicionar a paid y callback duplicado no duplica",async()=>{const sql=await readFile(migration,"utf8");assert.match(sql,/new\.status = 'paid' and old\.status is distinct from 'paid'/);assert.match(sql,/after update of status on public\.web_orders/);assert.match(sql,/on conflict\(order_id,event_type\) do nothing/);assert.doesNotMatch(sql,/insert into public\.web_order_email_events[\s\S]*payment_review/);});

test("claim es limitado, concurrente, reintentable e idempotente",async()=>{const sql=await readFile(migration,"utf8");assert.match(sql,/p_limit not between 1 and 50/);assert.match(sql,/for update skip locked/);assert.match(sql,/attempts < 5/);assert.match(sql,/status = 'sending' and event\.claimed_at < now\(\) - interval '15 minutes'/);assert.match(sql,/next_attempt_at=now\(\)\+\(least\(power\(2,event\.attempts\)/);});

test("RPC outbox son privadas y solo service_role ejecuta",async()=>{const sql=await readFile(migration,"utf8");for(const signature of ["claim_web_order_email_events\\(integer\\)","complete_web_order_email_event\\(uuid,text\\)","fail_web_order_email_event\\(uuid,text,text\\)"]){assert.match(sql,new RegExp(`revoke all on function public\\.${signature} from public, anon, authenticated`));assert.match(sql,new RegExp(`grant execute on function public\\.${signature} to service_role`));}});

test("cron exige secreto y expiración reutiliza RPC existente en lotes",async()=>{const auth=await read("src/lib/internal/cron-auth.ts"),route=await read("src/app/api/internal/maintenance/expire-payments/route.ts");assert.match(auth,/authorization/);assert.match(auth,/timingSafeEqual/);assert.match(auth,/secret\.length<32/);assert.match(route,/expire_web_pending_payments/);assert.match(route,/p_limit:100/);assert.match(route,/batches<5/);assert.doesNotMatch(route,/cookie|getAdministrativeSession/);});

test("expiración histórica mantiene locks, paid y stock intactos",async()=>{const old=await read("supabase/migrations/20260831225257_web_flow_payments.sql");const fn=old.slice(old.indexOf("create or replace function public.expire_web_pending_payments"),old.indexOf("create or replace function public.get_web_payment_result"));assert.match(fn,/orders\.status='pending_payment'/);assert.match(fn,/for update of orders,reservation skip locked/);assert.match(fn,/status='expired'/);assert.doesNotMatch(fn,/product_variants|set stock|orders\.status='paid'/);});

test("Resend usa idempotency key y no filtra credenciales",async()=>{const priorKey=process.env.RESEND_API_KEY,priorFrom=process.env.ORDER_EMAIL_FROM;process.env.RESEND_API_KEY="secret-test-value";process.env.ORDER_EMAIL_FROM="Columpio <test@example.com>";let request;const provider=createResendProvider(async(url,init)=>{request={url,init};return new Response(JSON.stringify({id:"email-1"}),{status:200,headers:{"content-type":"application/json"}});});const result=await provider.send({to:"buyer@example.com",subject:"Pedido",html:"<p>ok</p>",text:"ok",idempotencyKey:"order-paid/event"});assert.equal(result.id,"email-1");assert.equal(request.init.headers["idempotency-key"],"order-paid/event");assert.doesNotMatch(JSON.stringify(request.init.body),/secret-test-value/);if(priorKey===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=priorKey;if(priorFrom===undefined)delete process.env.ORDER_EMAIL_FROM;else process.env.ORDER_EMAIL_FROM=priorFrom;});

test("error Resend queda sanitizado y allowlisted",async()=>{const priorKey=process.env.RESEND_API_KEY,priorFrom=process.env.ORDER_EMAIL_FROM;process.env.RESEND_API_KEY="secret-test-value";process.env.ORDER_EMAIL_FROM="test@example.com";const provider=createResendProvider(async()=>new Response(JSON.stringify({name:"bad_request",message:"<b>Error</b>\u0000 detalle",secret:"must-not-leak"}),{status:400}));await assert.rejects(()=>provider.send({to:"x@example.com",subject:"x",html:"x",text:"x",idempotencyKey:"one"}),(error)=>{assert.ok(error instanceof EmailProviderError);assert.equal(error.code,"bad_request");assert.equal(error.message,"Error detalle");assert.doesNotMatch(`${error.code}${error.message}`,/must-not-leak|secret-test-value/);return true;});if(priorKey===undefined)delete process.env.RESEND_API_KEY;else process.env.RESEND_API_KEY=priorKey;if(priorFrom===undefined)delete process.env.ORDER_EMAIL_FROM;else process.env.ORDER_EMAIL_FROM=priorFrom;});

test("contenido y admin usan snapshots sin tokens ni payload Flow",async()=>{const email=await read("src/lib/email/order-confirmation.ts"),admin=await read("src/app/pedidos/[id]/page.tsx"),repo=await read("src/lib/admin/orders.ts");for(const field of ["web_order_customers","web_order_addresses","web_order_items"])assert.match(email,new RegExp(field));assert.doesNotMatch(email,/flow_token|web_payment_events|payload/);assert.match(admin,/EMAIL DE CONFIRMACIÓN/);assert.match(repo,/web_order_email_events/);});

test("logs de email no incluyen destinatario ni contenido",async()=>{const source=await read("src/lib/email/order-confirmation.ts");assert.match(source,/eventId:event\.event_id,orderNumber:content\.orderNumber/);assert.doesNotMatch(source,/logger\.(info|error)\([^\n]*\{[^}]*\b(recipient|to|html|text|email)\s*:/);});
