import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { FulfillmentActions } from "@/components/admin/fulfillment-actions";
import { getAdminOrder } from "@/lib/admin/orders";
import { getAdministrativeSession } from "@/lib/supabase/admin-auth";

const money=new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0});
const when=(value:unknown)=>typeof value==="string"?new Intl.DateTimeFormat("es-CL",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const value=(row:Record<string,unknown>|null,key:string)=>row?.[key]??"—";

export default async function OrderDetailPage({params}:{params:Promise<{id:string}>}){
  const {authorized}=await getAdministrativeSession();if(!authorized)redirect("/login");
  const {id}=await params;const order=await getAdminOrder(id);if(!order)notFound();
  const address=order.address;const customer=order.customer;
  return <div className="page-wrap order-detail"><Link href="/pedidos" className="back-link">← Volver a pedidos</Link><header className="page-header"><div><span className="eyebrow">PEDIDO WEB</span><h1>{order.orderNumber}</h1><p>Creado {when(order.createdAt)} · actualizado {when(order.updatedAt)}</p></div><div className="order-heading-status"><span className={`order-status ${order.paymentStatus}`}>{order.paymentStatus}</span><strong>{order.orderStatus}</strong><small>{order.fulfillmentStatus}</small></div></header>
    {(order.orderStatus==="payment_review"||order.stockException)&&<div className="order-alert"><strong>Revisión manual requerida</strong><span>{order.stockException?"El pago presenta una excepción de stock.":"El pedido está en revisión de pago."}</span></div>}
    <div className="order-detail-grid"><main><section className="order-card"><span className="eyebrow">PRODUCTOS · SNAPSHOT</span>{order.items.map((item)=><article className="order-item" key={String(item.id)}>{item.image_url?<span className="order-item-image" role="img" aria-label={String(item.product_name)} style={{backgroundImage:`url(${String(item.image_url)})`}}/>:<span className="order-item-placeholder"/>}<div><strong>{String(item.product_name)}</strong><small>{String(item.color)} · Talla {String(item.size)} · {String(item.variant_sku||"Sin SKU")}</small><span>{Number(item.quantity)} × {money.format(Number(item.final_unit_price))}</span></div><b>{money.format(Number(item.line_subtotal))}</b></article>)}<div className="order-totals"><span>Subtotal <b>{money.format(order.itemsSubtotal)}</b></span><span>Descuento <b>− {money.format(order.discountTotal)}</b></span><span>Despacho <b>{money.format(order.shippingTotal)}</b></span><strong>Total <b>{money.format(order.total)}</b></strong></div></section>
      <section className="order-card"><span className="eyebrow">PAGO FLOW</span>{order.payment?<div className="order-data-grid"><span>Estado<strong>{String(order.payment.status)}</strong></span><span>Monto<strong>{money.format(Number(order.payment.amount))}</strong></span><span>Pagado<strong>{when(order.payment.paid_at)}</strong></span><span>Excepción stock<strong>{order.stockException?"Sí":"No"}</strong></span></div>:<p>Pago aún no creado.</p>}<h3>Intentos</h3>{order.attempts.length?order.attempts.map((attempt)=><div className="timeline-row" key={String(attempt.id)}><strong>Intento {String(attempt.attempt_number)} · {String(attempt.status)}</strong><span>{String(attempt.commerce_order)} · {when(attempt.created_at)}</span>{Boolean(attempt.error_code)&&<small>{String(attempt.error_code)} · {String(attempt.error_message||"")}</small>}</div>):<p>Sin intentos.</p>}<h3>Eventos relevantes</h3>{order.paymentEvents.length?order.paymentEvents.map((event)=><div className="timeline-row" key={String(event.id)}><strong>{String(event.event_type)} · proveedor {String(event.provider_status)}</strong><span>Recibido {when(event.received_at)} · procesado {when(event.processed_at)}</span></div>):<p>Sin eventos.</p>}</section>
      <section className="order-card"><span className="eyebrow">AUDITORÍA ADMINISTRATIVA</span>{order.adminEvents.length?order.adminEvents.map((event)=><div className="timeline-row" key={String(event.id)}><strong>{String(event.from_status)} → {String(event.to_status)}</strong><span>{when(event.created_at)}</span>{Boolean(event.note)&&<small>{String(event.note)}</small>}</div>):<p>Aún no existen cambios administrativos.</p>}</section></main>
      <aside><FulfillmentActions orderId={order.id} orderStatus={order.orderStatus} paymentStatus={order.paymentStatus} stockException={order.stockException} deliveryType={order.deliveryType} fulfillmentStatus={order.fulfillmentStatus}/><section className="order-card"><span className="eyebrow">CLIENTE · SNAPSHOT</span><h2>{String(value(customer,"first_name"))} {String(value(customer,"last_name"))}</h2><p>{String(value(customer,"email"))}<br/>{String(value(customer,"phone"))}</p></section><section className="order-card"><span className="eyebrow">ENTREGA · SNAPSHOT</span><h2>{order.deliveryType==="pickup"?"Retiro":"Despacho"}</h2>{order.deliveryType==="shipping"?<p>{String(value(address,"recipient_name"))}<br/>{String(value(address,"street"))} {String(value(address,"street_number"))}<br/>{String(value(address,"commune"))}, {String(value(address,"region_name"))}</p>:<p>Retiro sin dirección de despacho.</p>}</section><section className="order-card"><span className="eyebrow">RESERVA</span>{order.reservation?<div className="order-data-grid"><span>Estado<strong>{String(order.reservation.status)}</strong></span><span>Vence<strong>{when(order.reservation.expires_at)}</strong></span><span>Consumida<strong>{when(order.reservation.consumed_at)}</strong></span></div>:<p>Sin reserva asociada.</p>}</section></aside></div>
  </div>;
}
