import type { MockCollection, MockProduct } from "./mock-types";

// BLOQUE WEB 1: datos ficticios y superficies temporales. No representan catálogo ni stock real de Supabase.
export const mockProducts: MockProduct[] = [
  { slug: "vestido-alba-terracota", name: "Vestido Alba", category: "Vestidos", categorySlug: "vestidos", description: "Vestido midi de líneas suaves, pensado para acompañarte desde una tarde luminosa hasta una cena especial.", details: ["Calce relajado", "Largo midi", "Caída liviana"], price: 49990, promotionalPrice: 39990, discountPercentage: 20, colors: ["Terracota", "Negro"], sizes: ["S", "M", "L"], availability: "Disponible", featured: true, newArrival: true, visual: "clay", images: ["clay", "sand", "rose"] },
  { slug: "vestido-bruma-negro", name: "Vestido Bruma", category: "Vestidos", categorySlug: "vestidos", description: "Una silueta negra atemporal con movimiento sutil y escote limpio.", details: ["Tela fluida", "Manga corta", "Terminación limpia"], price: 45990, colors: ["Negro"], sizes: ["S", "M", "L", "XL"], availability: "Pocas unidades", featured: false, newArrival: false, visual: "ink", images: ["ink", "stone"] },
  { slug: "blusa-amelia-marfil", name: "Blusa Amelia", category: "Blusas", categorySlug: "blusas", description: "Blusa marfil de textura delicada y volumen femenino para elevar los esenciales.", details: ["Cuello suave", "Manga amplia", "Textura ligera"], price: 32990, colors: ["Marfil", "Rosa viejo"], sizes: ["S", "M", "L"], availability: "Disponible", featured: true, newArrival: true, visual: "ivory", images: ["ivory", "rose"] },
  { slug: "blusa-noa-celeste", name: "Blusa Noa", category: "Blusas", categorySlug: "blusas", description: "Una blusa fresca y versátil para combinar con denim o sastrería.", details: ["Calce regular", "Botones nacarados", "Tacto suave"], price: 29990, colors: ["Celeste", "Blanco"], sizes: ["S", "M", "L", "XL"], availability: "Disponible", featured: false, newArrival: false, visual: "sky", images: ["sky", "ivory"] },
  { slug: "polera-luz-crudo", name: "Polera Luz", category: "Poleras", categorySlug: "poleras", description: "Base esencial de algodón suave con una silueta femenina y limpia.", details: ["Algodón suave", "Cuello redondo", "Calce regular"], price: 18990, promotionalPrice: 15990, discountPercentage: 16, colors: ["Crudo", "Chocolate"], sizes: ["S", "M", "L", "XL"], availability: "Disponible", featured: true, newArrival: false, visual: "oat", images: ["oat", "cocoa"] },
  { slug: "polera-ama-rosa", name: "Polera Ama", category: "Poleras", categorySlug: "poleras", description: "Un toque rosado y cálido para looks relajados de todos los días.", details: ["Jersey liviano", "Calce levemente holgado", "Manga corta"], price: 19990, colors: ["Rosa", "Blanco"], sizes: ["S", "M", "L"], availability: "Próximamente", featured: false, newArrival: true, visual: "rose", images: ["rose", "ivory"] },
  { slug: "pantalon-elena-taupe", name: "Pantalón Elena", category: "Pantalones", categorySlug: "pantalones", description: "Pantalón sastrero de tiro alto y pierna amplia, elegante sin perder comodidad.", details: ["Tiro alto", "Pierna recta", "Bolsillos laterales"], price: 39990, colors: ["Taupe", "Negro"], sizes: ["36", "38", "40", "42"], availability: "Disponible", featured: true, newArrival: true, visual: "taupe", images: ["taupe", "ink"] },
  { slug: "pantalon-mara-negro", name: "Pantalón Mara", category: "Pantalones", categorySlug: "pantalones", description: "Una base negra pulida para construir looks de oficina y fin de semana.", details: ["Tela elasticada", "Tiro medio", "Pierna levemente amplia"], price: 36990, colors: ["Negro"], sizes: ["36", "38", "40", "42", "44"], availability: "Disponible", featured: false, newArrival: false, visual: "charcoal", images: ["charcoal", "stone"] },
  { slug: "blazer-emma-avellana", name: "Blazer Emma", category: "Chaquetas", categorySlug: "chaquetas", description: "Blazer de estructura liviana en un tono avellana cálido y combinable.", details: ["Solapa clásica", "Forro liviano", "Calce semi holgado"], price: 59990, promotionalPrice: 50990, discountPercentage: 15, colors: ["Avellana", "Negro"], sizes: ["S", "M", "L"], availability: "Pocas unidades", featured: true, newArrival: true, visual: "hazel", images: ["hazel", "sand", "ink"] },
  { slug: "cartera-mini-olivia", name: "Cartera Mini Olivia", category: "Accesorios", categorySlug: "accesorios", description: "Cartera compacta de textura suave para acompañar tus esenciales.", details: ["Correa ajustable", "Cierre superior", "Interior forrado"], price: 27990, colors: ["Chocolate", "Negro"], sizes: ["Única"], availability: "Disponible", featured: true, newArrival: false, visual: "cocoa", images: ["cocoa", "ink"] },
];

export const mockCollections: MockCollection[] = [
  { slug: "vestidos", name: "Vestidos", description: "Siluetas femeninas para momentos cotidianos y ocasiones especiales.", visual: "clay" },
  { slug: "blusas", name: "Blusas", description: "Texturas suaves y detalles que transforman cada combinación.", visual: "ivory" },
  { slug: "poleras", name: "Poleras", description: "Esenciales cómodos con el sello cálido de Columpio.", visual: "rose" },
  { slug: "pantalones", name: "Pantalones", description: "Calces contemporáneos para vestir a tu manera.", visual: "taupe" },
  { slug: "chaquetas", name: "Chaquetas", description: "Capas versátiles que completan tu look.", visual: "hazel" },
  { slug: "accesorios", name: "Accesorios", description: "Pequeños acentos para hacer tuyo cada outfit.", visual: "cocoa" },
];

export const getMockProduct = (slug: string) => mockProducts.find((product) => product.slug === slug);
export const getMockCollection = (slug: string) => mockCollections.find((collection) => collection.slug === slug);
export const productsForCollection = (slug: string) => mockProducts.filter((product) => product.categorySlug === slug);
